# Generated by Django 5.0.4 on 2024-05-12 12:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0004_address_zip'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='customer',
            table='store_customer',
        ),
    ]
