# Generated by Django 5.0.4 on 2024-05-12 12:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0005_alter_customer_table'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='customer',
            table=None,
        ),
    ]
